### PR TITLE
Integration of parallel (GPU) Smith Waterman

### PR DESCRIPTION
**Pull request by benjaminsaljooghi**
This is a new project `BioFSharp.Parallel` containing a parallelization of this repository's Smith Waterman algorithm using Alea GPU. The project requires Alea GPU to be installed via NuGet. Currently, the project only contains a Smith Waterman algorithm, executed via its `run` function (at the bottom). In subsequent commits I would like to make the following improvements:

- Adding the Needleman Wunsch algorithm.
- Parameterization of the scoring system via the substitution matrix / gap-scoring scheme in `ScoringMatrix.fs`.
- Changing the `run` parameters from strings to the `BioArray` format.
- Refactoring.

Afterwards, I am thinking about removing the Smith Waterman and Needleman Wunsch algorithms, and instead changing the rest of this project to be a generalized, parallel `createCellMatrix`. This would then be usable by the Smith Waterman and Needleman Wunch algorithms in `PairwiseAlignment.fs`.

The grid size for `LaunchParam` must currently remain 1 because more than one block will cause synchronization issues. This is due to the CUDA call `__syncthreads()` only synchronizing threads within blocks, not all threads across the grid. Despite this, this parallelization results in a _significant_ performance improvement for large sequence sizes while still returning an identical alignment to the Smith Waterman algorithm in `PairwiseAlignment.fs` for the same input.

In this pull request I have also restored the `maxBy2` function in its inline form as suggested by [ZimmerD here](https://github.com/CSBiology/BioFSharp/commit/282eaf66d06a095ace9b66ce6edeadcac63c3c24). After some testing, I determined that my `List.maxBy` version is actually slower compared to the inline `maxBy2`, and it also causes the alignments to be different.

### CODE REVIEW

**Comment by HLWeil** [comment]
TODO: 
-Move the new project to /src/ and include it in the solution
-include Alea with .paket

**Comment by benjaminsaljooghi** [comment]
TODO:
- [X] Move the new project to /src/ and include it in the solution
- [X] include Alea with .paket
- [ ] Add the Needleman Wunsch algorithm.
- [ ] Parameterize the scoring system via the substitution matrix / gap-scoring scheme in ScoringMatrix.fs.
- [ ] Change the run parameters from strings to the BioArray format.
- [ ] Refactoring.
- [ ] Remove the Smith Waterman and Needleman Wunsch algorithms, and instead change the rest of this project to be a generalized, parallel createCellMatrix. This would then be usable by the Smith Waterman and Needleman Wunch algorithms in PairwiseAlignment.fs.

**Comment by HLWeil** [comment]
I'd say as long as the project is buildable and fits into the repository structure and style (which is the case now) its mergeable. But when I tried to run the new function I got the following error: 
`BioFSharp.Parallel.PairwiseAlignment.SmithWaterman.run "HELLO" "HELLOO"`

> System.UnauthorizedAccessException: Access to the path 'C:\Program Files (x86)\Microsoft SDKs\F#\4.1\Framework\v4.0\Alea.CUDA.CT.Native.X86.B32.Windows' is denied.
>    at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
>    at System.IO.Directory.InternalCreateDirectory(String fullPath, String path, Object dirSecurityObj, Boolean checkHost)
>    at System.IO.Directory.InternalCreateDirectoryHelper(String path, Boolean checkHost)
>    at System.IO.Directory.CreateDirectory(String path)
>    at Alea.InteropUtil.c4ff2f72e185b3a2f7c2a2597e6eff3b3(String c702cbfa0898e710c92cc7f8405a5f10b)
>    at A.ce1f0b8fd1a8427c49c9974839fd24a47.-ctor@103-5.Invoke(Unit _arg2)
>    at System.Lazy`1.CreateValue()
>    at System.Lazy`1.LazyInitValue()
>    at System.Lazy`1.get_Value()
>    at Alea.InteropUtil.c743cf16137d0a4c209718ffea8d6850f[cc42f98d07a24d11ea3365c05cc62bccb](String cc4c13872981961b5f9f0280454c95d5e, Type c1bb15b9697d679dbdeaa09f08af21136, Type[] ce055af2e4d8a3de85814c67bfb961318)
>    at Alea.LLVMInterop.LLVMContextCreate'@422.Invoke(Unit _arg1)
>    at System.Lazy`1.CreateValue()
>    at System.Lazy`1.LazyInitValue()
>    at System.Lazy`1.get_Value()
>    at Alea.Constructs.IRContext..ctor(Boolean c0ccc07ae94eaaf62dc93b35058efcd2d)
>    at Alea.IRModuleBuildingContext..ctor(CompileOptions compileOptions, FSharpOption`1 bitcodeCache, FSharpOption`1 moduleInfoCache, Boolean threadSafe)
>    at Alea.Compiler.ca9f5d6f172bf78b422b024bfca1e0e88[cc42f98d07a24d11ea3365c05cc62bccb](Template`1 c8575ef61e181c85fa1c8f6e6ebfd11a7, CompileOptions cd6e9ea30c11ed92c7a99d20c1e597355, FSharpOption`1 cdaa6e4e24dea3ca66291f08a869eec1c, FSharpOption`1 ca61c122af7c01e242ba334cc3c9b69df)
>    at Alea.Gpu.LoadProgram[T](Template`1 template, CompileOptions options)
>    at A.cf5aded17df9f7cc4c132234dda010fa7.c29aa5e7032675157e33c1dc0b645dc6d[cc42f98d07a24d11ea3365c05cc62bccb](Gpu c5f29de75421c4edf2675ba79bea2fe26, Template`1 c8575ef61e181c85fa1c8f6e6ebfd11a7, Object c4b3c7c9a9f5e8268551a9ccc7721f5a6)
>    at A.cf5aded17df9f7cc4c132234dda010fa7.EntryOf@3816.c8e2d32e46b41e9ecfa2d00a079eecc7c(Object c9b112fae5ec34cb254e091efcee6a421)
>    at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
>    at Alea.Gpu.EntryOf[T](Template`1 template)
>    at BioFSharp.Parallel.PairwiseAlignment.ParallelMatrix.gpuCellMatrix(Int32[] fst_seq, Int32[] snd_seq)
>    at BioFSharp.Parallel.PairwiseAlignment.SmithWaterman.run(String fstSeq, String sndSeq)
>    at <StartupCode$FSI_0002>.$FSI_0002.main@()
> Stopped due to error

Is this a to-be-expected error? If so then I'd say at least the documentation should be included with the pull request. If not then this should be fixed first. 

Maybe this is of help: 
-Win10 Pro 64bit
-32bit fsi.exe 
-Nvidia Geforce 940M
-The graphics card does turn on when I run the function and it does tell me the fsi.exe is using it. This does not stop automatically

**Comment by benjaminsaljooghi** [comment]
The postbuild event https://github.com/CSBiology/BioFSharp/pull/22/commits/67bff2e152899b484014af763898012a2d732211 is giving me an error during the build:

```
Build Time Report
---------------------------------------------------------------------
Target         Duration
------         --------
Clean          00:00:00.0041084
AssemblyInfo   00:00:00.0721686
Build          Failure
Total:         00:00:13.9785994
---------------------------------------------------------------------
Status:        Failure
---------------------------------------------------------------------
---------------------------------------------------------------------
  1) Building C:\projects\BioFSharp\BioFSharp\BioFSharp.sln failed with exitcode 1.
  2) MSB3073: C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets(5020,5): The command "xcopy /Y "C:\projects\BioFSharp\BioFSharp\src\BioFSharp.Parallel\bin\Release\*.dll"  "C:\projects\BioFSharp\BioFSharp\bin\"xcopy /Y "C:\projects\BioFSharp\BioFSharp\src\BioFSharp.Parallel\bin\Release\*.xml" "C:\projects\BioFSharp\BioFSharp\bin\"" exited with code 4.
```

If I revert to the previous commit https://github.com/CSBiology/BioFSharp/pull/22/commits/646b22ccd2a32db1cee2e5f38b3a30b836022c8f I am able to execute `Parallel.PairwiseAlignment.SmithWaterman.run` with a new Console Application project containing the following program. This project must reference `BioFSharp` and `BioFSharp.Parallel`. It also needs an `Alea` reference but I just chose to install Alea in the project via NuGet.

```F#
open BioFSharp
open BioFSharp.Algorithm
open PairwiseAlignment
open BioFSharp.Parallel
open System

let random = System.Random()
let random_sequence length =
    let random_nucleotide () =
        [|'A'; 'C'; 'G'; 'T'|].[random.Next(4)]
    System.String [| for i in 0..length-1 -> random_nucleotide () |]

let nucConversion (nucs:Nucleotides.Nucleotide list) =
    nucs |> List.map (fun element -> if string element = "Gap" then "-" else string element) |> String.Concat

let execute_parallel seq1 seq2 =
    let t = System.Diagnostics.Stopwatch.StartNew()
    let parallelAlignment = Parallel.PairwiseAlignment.SmithWaterman.run seq1 seq2
    t.Stop()
    
    printfn "execution time of parallel: %A" t.Elapsed
    parallelAlignment

let execute_sequential seq1 seq2 =
    let nucScoring = ScoringMatrix.getScoringMatrixNucleotide  ScoringMatrix.ScoringMatrixNucleotide.EDNA
    let nucCosts = {
        Open = -5
        Continuation = -1
        Similarity = nucScoring 
        }

    let seq1 = seq1 |> BioArray.ofNucleotideString
    let seq2 = seq2 |> BioArray.ofNucleotideString

    let t = System.Diagnostics.Stopwatch.StartNew()
    let sequentialAlignment = PairwiseAlignment.SmithWaterman.runNucleotide nucCosts seq1 seq2
    t.Stop()
   
    printfn "execution time of sequential: %A" t.Elapsed
    sequentialAlignment

[<EntryPoint>]
let main argv = 
    let seq1 = random_sequence 5
    let seq2 = random_sequence 5

    let parallelAlignment = execute_parallel seq1 seq2
    let sequentialAlignment = (execute_sequential seq1 seq2).AlignedSequences
    let sequentialAlignment = (sequentialAlignment.[0] |> nucConversion, sequentialAlignment.[1] |> nucConversion)

    printfn "parallel: %A" parallelAlignment
    printfn "sequential: %A" sequentialAlignment

    printfn "alignments equal: %A" (parallelAlignment = sequentialAlignment)

    0
```

**Comment by HLWeil** [comment]
Sry for the unncessary mistake on the postbuildevent. It should be fixed now. 

I managed to get the program to run as a console application. Though I had to copy **Alea.CUDA.CT.LibDevice.dll** and **Alea.CUDA.CT.Native.X86.B32.Windows.dll** manually from **\packages\Alea\tools** to **\ParallelTest\bin\Debug**.
When I try to run the code directly in an editor using fsi I get the aforementioned error. It tries to use the dll from **C:\Program Files (x86)\Microsoft SDKs\F#\4.1\Framework\v4.0\Alea.CUDA.CT.Native.X86.B32.Windows** instead, but naturally fails cause of the missing permission.

Do you know what might be the reason for this?

**Comment by benjaminsaljooghi** [comment]
Got it! I'm so happy! Try the new script I just commited

**Comment by HLWeil** [comment]
Nice! It does work with that line. 
I will merge this pull request now. For the purpose of tidiness I will open a new team-project to transfer the TODO-list there.

**Pull request merged**
