### PR TITLE
FSharp.Care and FSharp.Stats submodules

### LINKED ISSUE #23: Should FSharp.Care and FSharp.Stats be added as submodules?
Should FSharp.Care and FSharp.Stats be added as [submodules](https://git-scm.com/book/en/v2/Git-Tools-Submodules)? This would make it more convenient to build this repository after cloning it.

### PR DESCRIPTION
**Pull request by benjaminsaljooghi**
This pull request closes #23 by adding repositories [FSharp.Care](https://github.com/CSBiology/FSharp.Care) and [FSharp.Stats](https://github.com/CSBiology/FSharp.Stats) as [submodules](https://git-scm.com/book/en/v2/Git-Tools-Submodules).

This involves a big change to the structure of this repository. In the root, I add the submodules via 
```
git submodule add https://github.com/CSBiology/FSharp.Care.git
git submodule add https://github.com/CSBiology/FSharp.Stats.git
```
Also in the root, I have kept the `README.md`, but I have moved everything else into a folder called `BioFSharp`.

The end result looks like this:

image

To build this repository, previously, you would need to separately clone FSharp.Care, FSharp.Stats, and BioFSharp before building.

```
git clone https://github.com/CSBiology/BioFSharp.git
git clone https://github.com/CSBiology/FSharp.Care.git
git clone https://github.com/CSBiology/FSharp.Stats.git
.\BioFSharp\build.cmd
```

But now you can just clone the single repository, update the submodules, and build.

```
git clone https://github.com/CSBiology/BioFSharp.git
cd .\BioFSharp\
git submodule init
git submodule update
.\build.cmd
```

This a big change to the repository structure though, so I understand if this change is not ideal. However, I do like this change because now the build process is more obvious to new contributors, and you don't need to create separate folders for the two required libraries.

Note that, by using submodules, we are still keeping the development of FSharp.Care, FSharp.Stats, and BioFSharp completely separate and modular. If a change is made to FSharp.Care, for example, and you want the new changes in BioFSharp, you just need to run `git submodule update`.

### CODE REVIEW

**Comment by HLWeil** [comment]
Thanks for your efforts on this topic. 

I have read up on the tutorial [link](https://git-scm.com/book/en/v2/Git-Tools-Submodules) you posted in #23. I must say just judging by this I'm not quite sure if this will improve the handling. To be a bit more precise: 

Receiving is much easier when using submodules. All you have to do for this is stated in your initial comment. Contributing on the other hand is a different story. Especially pushing local commits of changes made to the submodules might be quite some fiddly work.

Therefore I suggest we should rather test this first on a dedicated branch (e.g. called submodule-testing). This would allow for field testing while maintaining the already aquired comfort other developers have.

**Comment by benjaminsaljooghi** [comment]
Contributing to the submodules would still be exactly the same as before. The repositories here https://github.com/CSBiology/FSharp.Care and here https://github.com/CSBiology/FSharp.Stats would continue to exist and you would just commit to them the way contributors have been.

**Comment by benjaminsaljooghi** [comment]
And also, actually, I just did some Googling and found [this](https://stackoverflow.com/questions/5542910/how-do-i-commit-changes-in-a-git-submodule) which is a convenient way of contributing to submodules

**Comment by benjaminsaljooghi** [comment]
Though this pull request could be complicating things too much. Up to you.

**Comment by kMutagene** [comment]
Hi @benjaminsaljooghi , 
as you already saw in the corresponding [issue](https://github.com/CSBiology/BioFSharp/issues/23), We took the route of serving nuget packages via github for now (a4085bdc150477319e2f32462b0e9b1613caebe5 ).

Nonetheless, i want to thank you for your efforts!

**Comment by benjaminsaljooghi** [comment]
Hey no worries! I might come back one day and see where I can help out again :)

**Comment by kMutagene** [comment]
That would be highly appreciated!
We are in a way more productive state now and i will put some up-for-grabs issues into our main projects, so feel free to check them out from time to time ;)

**Pull request closed without merging**
